name = "HubGS"
type = "language"
file_types = ["hubgs"]
scope_name = "source.hubgs"
grammar = "hubgs"

[line_comments]
start = "//"

[block_comments]
start = "/*"
end = "*/"

[indentation]
increase_pattern = "\\{\\s*$"
decrease_pattern = "^\\s*\\}"
