/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 1
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LTdocument_GT = 1,
  anon_sym_LT_SLASHdocument_GT = 2,
  anon_sym_LTbody_GT = 3,
  anon_sym_LT_SLASHbody_GT = 4,
  anon_sym_LT = 5,
  anon_sym_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_SLASH_GT = 8,
  anon_sym_EQ = 9,
  aux_sym_tag_name_token1 = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_attribute_value_token1 = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_attribute_value_token2 = 14,
  sym_text = 15,
  anon_sym_LT_BANG_DASH_DASH = 16,
  aux_sym_comment_token1 = 17,
  anon_sym_DASH_DASH_GT = 18,
  sym_source_file = 19,
  sym_document_block = 20,
  sym_body_block = 21,
  sym_element = 22,
  sym_start_tag = 23,
  sym_end_tag = 24,
  sym_self_closing_element = 25,
  sym_attribute = 26,
  sym_tag_name = 27,
  sym_attribute_name = 28,
  sym_attribute_value = 29,
  sym_comment = 30,
  aux_sym_document_block_repeat1 = 31,
  aux_sym_body_block_repeat1 = 32,
  aux_sym_element_repeat1 = 33,
  aux_sym_start_tag_repeat1 = 34,
  aux_sym_comment_repeat1 = 35,
  alias_sym_meta_tag = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LTdocument_GT] = "<document>",
  [anon_sym_LT_SLASHdocument_GT] = "</document>",
  [anon_sym_LTbody_GT] = "<body>",
  [anon_sym_LT_SLASHbody_GT] = "</body>",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_EQ] = "=",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_attribute_value_token1] = "attribute_value_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_value_token2] = "attribute_value_token2",
  [sym_text] = "text",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_source_file] = "source_file",
  [sym_document_block] = "document_block",
  [sym_body_block] = "body_block",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_element] = "self_closing_element",
  [sym_attribute] = "attribute",
  [sym_tag_name] = "tag_name",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_comment] = "comment",
  [aux_sym_document_block_repeat1] = "document_block_repeat1",
  [aux_sym_body_block_repeat1] = "body_block_repeat1",
  [aux_sym_element_repeat1] = "element_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [alias_sym_meta_tag] = "meta_tag",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LTdocument_GT] = anon_sym_LTdocument_GT,
  [anon_sym_LT_SLASHdocument_GT] = anon_sym_LT_SLASHdocument_GT,
  [anon_sym_LTbody_GT] = anon_sym_LTbody_GT,
  [anon_sym_LT_SLASHbody_GT] = anon_sym_LT_SLASHbody_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_value_token2] = aux_sym_attribute_value_token2,
  [sym_text] = sym_text,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_source_file] = sym_source_file,
  [sym_document_block] = sym_document_block,
  [sym_body_block] = sym_body_block,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_element] = sym_self_closing_element,
  [sym_attribute] = sym_attribute,
  [sym_tag_name] = sym_tag_name,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_comment] = sym_comment,
  [aux_sym_document_block_repeat1] = aux_sym_document_block_repeat1,
  [aux_sym_body_block_repeat1] = aux_sym_body_block_repeat1,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [alias_sym_meta_tag] = alias_sym_meta_tag,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LTdocument_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHdocument_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LTbody_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHbody_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_document_block] = {
    .visible = true,
    .named = true,
  },
  [sym_body_block] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_element] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_meta_tag] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_meta_tag,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_self_closing_element, 2,
    sym_self_closing_element,
    alias_sym_meta_tag,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 25,
  [35] = 35,
  [36] = 27,
  [37] = 37,
  [38] = 31,
  [39] = 35,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 37,
  [44] = 35,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 48,
  [50] = 45,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '<') ADVANCE(44);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == '>') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(64);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '<') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(14);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '<') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(63);
      END_STATE();
    case 8:
      if (lookahead == '<') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(63);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(39);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(42);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(70);
      END_STATE();
    case 15:
      if (lookahead == 'b') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 35:
      if (lookahead == 'y') ADVANCE(10);
      END_STATE();
    case 36:
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 37:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(63);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LTdocument_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT_SLASHdocument_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LTbody_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_SLASHbody_GT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '/') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == 'b') ADVANCE(27);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '!') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '<') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '!') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '<') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(56);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(62);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '!') ADVANCE(4);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '<') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 61},
  [57] = {.lex_state = 55},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {(TSStateId)(-1),},
  [68] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LTbody_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_tag_name_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(60),
    [sym_document_block] = STATE(64),
    [sym_comment] = STATE(1),
    [anon_sym_LTdocument_GT] = ACTIONS(5),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_SLASH,
    ACTIONS(11), 1,
      sym_text,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_element_repeat1,
    STATE(5), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_end_tag,
    STATE(24), 2,
      sym_element,
      sym_self_closing_element,
  [29] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_SLASH,
    ACTIONS(11), 1,
      sym_text,
    STATE(3), 1,
      sym_comment,
    STATE(5), 1,
      sym_start_tag,
    STATE(9), 1,
      aux_sym_element_repeat1,
    STATE(27), 1,
      sym_end_tag,
    STATE(24), 2,
      sym_element,
      sym_self_closing_element,
  [58] = 9,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      sym_text,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      sym_start_tag,
    STATE(9), 1,
      aux_sym_element_repeat1,
    STATE(36), 1,
      sym_end_tag,
    STATE(24), 2,
      sym_element,
      sym_self_closing_element,
  [87] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      sym_text,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    STATE(4), 1,
      aux_sym_element_repeat1,
    STATE(34), 1,
      sym_end_tag,
    STATE(5), 2,
      sym_start_tag,
      sym_comment,
    STATE(24), 2,
      sym_element,
      sym_self_closing_element,
  [114] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(15), 1,
      anon_sym_LT_SLASHbody_GT,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_body_block_repeat1,
    STATE(21), 2,
      sym_element,
      sym_self_closing_element,
  [140] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      sym_text,
    ACTIONS(21), 1,
      anon_sym_LT_SLASHbody_GT,
    STATE(2), 1,
      sym_start_tag,
    STATE(7), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_body_block_repeat1,
    STATE(21), 2,
      sym_element,
      sym_self_closing_element,
  [166] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(23), 1,
      anon_sym_LT_SLASHbody_GT,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(28), 1,
      sym_text,
    STATE(2), 1,
      sym_start_tag,
    STATE(8), 2,
      sym_comment,
      aux_sym_body_block_repeat1,
    STATE(21), 2,
      sym_element,
      sym_self_closing_element,
  [190] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(31), 1,
      anon_sym_LT,
    ACTIONS(34), 1,
      anon_sym_LT_SLASH,
    ACTIONS(36), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(9), 2,
      sym_comment,
      aux_sym_element_repeat1,
    STATE(24), 2,
      sym_element,
      sym_self_closing_element,
  [214] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(39), 1,
      anon_sym_GT,
    ACTIONS(41), 1,
      anon_sym_SLASH_GT,
    ACTIONS(43), 1,
      aux_sym_tag_name_token1,
    STATE(10), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_start_tag_repeat1,
    STATE(26), 1,
      sym_attribute,
    STATE(65), 1,
      sym_attribute_name,
  [239] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(39), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      aux_sym_tag_name_token1,
    ACTIONS(45), 1,
      anon_sym_SLASH_GT,
    STATE(11), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_start_tag_repeat1,
    STATE(26), 1,
      sym_attribute,
    STATE(65), 1,
      sym_attribute_name,
  [264] = 6,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(49), 1,
      aux_sym_tag_name_token1,
    STATE(26), 1,
      sym_attribute,
    STATE(65), 1,
      sym_attribute_name,
    ACTIONS(47), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(12), 2,
      sym_comment,
      aux_sym_start_tag_repeat1,
  [285] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(43), 1,
      aux_sym_tag_name_token1,
    ACTIONS(52), 1,
      anon_sym_GT,
    ACTIONS(54), 1,
      anon_sym_SLASH_GT,
    STATE(12), 1,
      aux_sym_start_tag_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(26), 1,
      sym_attribute,
    STATE(65), 1,
      sym_attribute_name,
  [310] = 8,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(43), 1,
      aux_sym_tag_name_token1,
    ACTIONS(52), 1,
      anon_sym_GT,
    ACTIONS(56), 1,
      anon_sym_SLASH_GT,
    STATE(12), 1,
      aux_sym_start_tag_repeat1,
    STATE(14), 1,
      sym_comment,
    STATE(26), 1,
      sym_attribute,
    STATE(65), 1,
      sym_attribute_name,
  [335] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(58), 1,
      anon_sym_LTbody_GT,
    ACTIONS(60), 1,
      anon_sym_LT,
    STATE(15), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_document_block_repeat1,
    STATE(47), 1,
      sym_self_closing_element,
    STATE(54), 1,
      sym_body_block,
  [357] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(43), 1,
      aux_sym_tag_name_token1,
    ACTIONS(62), 1,
      anon_sym_SLASH_GT,
    STATE(16), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_start_tag_repeat1,
    STATE(26), 1,
      sym_attribute,
    STATE(65), 1,
      sym_attribute_name,
  [379] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(58), 1,
      anon_sym_LTbody_GT,
    ACTIONS(60), 1,
      anon_sym_LT,
    STATE(17), 1,
      sym_comment,
    STATE(19), 1,
      aux_sym_document_block_repeat1,
    STATE(47), 1,
      sym_self_closing_element,
    STATE(52), 1,
      sym_body_block,
  [401] = 7,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(43), 1,
      aux_sym_tag_name_token1,
    ACTIONS(64), 1,
      anon_sym_SLASH_GT,
    STATE(12), 1,
      aux_sym_start_tag_repeat1,
    STATE(18), 1,
      sym_comment,
    STATE(26), 1,
      sym_attribute,
    STATE(65), 1,
      sym_attribute_name,
  [423] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(66), 1,
      anon_sym_LTbody_GT,
    ACTIONS(68), 1,
      anon_sym_LT,
    STATE(47), 1,
      sym_self_closing_element,
    STATE(19), 2,
      sym_comment,
      aux_sym_document_block_repeat1,
  [440] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(71), 1,
      anon_sym_LT,
    STATE(20), 1,
      sym_comment,
    ACTIONS(73), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [454] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(77), 1,
      anon_sym_LT,
    STATE(21), 1,
      sym_comment,
    ACTIONS(75), 2,
      anon_sym_LT_SLASHbody_GT,
      sym_text,
  [468] = 5,
    ACTIONS(79), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(81), 1,
      aux_sym_comment_token1,
    ACTIONS(83), 1,
      anon_sym_DASH_DASH_GT,
    STATE(22), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_comment_repeat1,
  [484] = 5,
    ACTIONS(79), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(81), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_DASH_DASH_GT,
    STATE(22), 1,
      aux_sym_comment_repeat1,
    STATE(23), 1,
      sym_comment,
  [500] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(87), 1,
      anon_sym_LT,
    STATE(24), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [514] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(93), 1,
      anon_sym_LT,
    STATE(25), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_LT_SLASHbody_GT,
      sym_text,
  [528] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
  [540] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(99), 1,
      anon_sym_LT,
    STATE(27), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_LT_SLASHbody_GT,
      sym_text,
  [554] = 4,
    ACTIONS(79), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(101), 1,
      aux_sym_comment_token1,
    ACTIONS(104), 1,
      anon_sym_DASH_DASH_GT,
    STATE(28), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [568] = 5,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(106), 1,
      anon_sym_DQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE,
    STATE(29), 1,
      sym_comment,
    STATE(32), 1,
      sym_attribute_value,
  [584] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(110), 1,
      anon_sym_LT,
    STATE(30), 1,
      sym_comment,
    ACTIONS(112), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [598] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(116), 1,
      anon_sym_LT,
    STATE(31), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_LT_SLASHbody_GT,
      sym_text,
  [612] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(118), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
  [624] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(120), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
  [636] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(93), 1,
      anon_sym_LT,
    STATE(34), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [650] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(124), 1,
      anon_sym_LT,
    STATE(35), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_LT_SLASHbody_GT,
      sym_text,
  [664] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(99), 1,
      anon_sym_LT,
    STATE(36), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [678] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(128), 1,
      anon_sym_LT,
    STATE(37), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_LT_SLASHbody_GT,
      sym_text,
  [692] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(116), 1,
      anon_sym_LT,
    STATE(38), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [706] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(124), 1,
      anon_sym_LT,
    STATE(39), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [720] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(128), 1,
      anon_sym_LT,
    STATE(40), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_LT_SLASH,
      sym_text,
  [734] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(41), 1,
      sym_comment,
    ACTIONS(130), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
  [746] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(132), 1,
      aux_sym_tag_name_token1,
    STATE(16), 1,
      sym_tag_name,
    STATE(42), 1,
      sym_comment,
  [759] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(126), 1,
      anon_sym_LTbody_GT,
    ACTIONS(128), 1,
      anon_sym_LT,
    STATE(43), 1,
      sym_comment,
  [772] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(122), 1,
      anon_sym_LTbody_GT,
    ACTIONS(124), 1,
      anon_sym_LT,
    STATE(44), 1,
      sym_comment,
  [785] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(132), 1,
      aux_sym_tag_name_token1,
    STATE(45), 1,
      sym_comment,
    STATE(61), 1,
      sym_tag_name,
  [798] = 3,
    ACTIONS(79), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(46), 1,
      sym_comment,
    ACTIONS(134), 2,
      aux_sym_comment_token1,
      anon_sym_DASH_DASH_GT,
  [809] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(136), 1,
      anon_sym_LTbody_GT,
    ACTIONS(138), 1,
      anon_sym_LT,
    STATE(47), 1,
      sym_comment,
  [822] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(132), 1,
      aux_sym_tag_name_token1,
    STATE(10), 1,
      sym_tag_name,
    STATE(48), 1,
      sym_comment,
  [835] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(132), 1,
      aux_sym_tag_name_token1,
    STATE(11), 1,
      sym_tag_name,
    STATE(49), 1,
      sym_comment,
  [848] = 4,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(132), 1,
      aux_sym_tag_name_token1,
    STATE(50), 1,
      sym_comment,
    STATE(62), 1,
      sym_tag_name,
  [861] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(140), 1,
      anon_sym_EQ,
    STATE(51), 1,
      sym_comment,
  [871] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(142), 1,
      anon_sym_LT_SLASHdocument_GT,
    STATE(52), 1,
      sym_comment,
  [881] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(144), 1,
      anon_sym_LT_SLASHdocument_GT,
    STATE(53), 1,
      sym_comment,
  [891] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(146), 1,
      anon_sym_LT_SLASHdocument_GT,
    STATE(54), 1,
      sym_comment,
  [901] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(148), 1,
      anon_sym_LT_SLASHdocument_GT,
    STATE(55), 1,
      sym_comment,
  [911] = 3,
    ACTIONS(79), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(150), 1,
      aux_sym_attribute_value_token2,
    STATE(56), 1,
      sym_comment,
  [921] = 3,
    ACTIONS(79), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(152), 1,
      aux_sym_attribute_value_token1,
    STATE(57), 1,
      sym_comment,
  [931] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      sym_comment,
  [941] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(154), 1,
      anon_sym_SQUOTE,
    STATE(59), 1,
      sym_comment,
  [951] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      sym_comment,
  [961] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(158), 1,
      anon_sym_GT,
    STATE(61), 1,
      sym_comment,
  [971] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(160), 1,
      anon_sym_GT,
    STATE(62), 1,
      sym_comment,
  [981] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    STATE(63), 1,
      sym_comment,
  [991] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      sym_comment,
  [1001] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(166), 1,
      anon_sym_EQ,
    STATE(65), 1,
      sym_comment,
  [1011] = 3,
    ACTIONS(3), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    STATE(66), 1,
      sym_comment,
  [1021] = 1,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
  [1025] = 1,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 114,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 166,
  [SMALL_STATE(9)] = 190,
  [SMALL_STATE(10)] = 214,
  [SMALL_STATE(11)] = 239,
  [SMALL_STATE(12)] = 264,
  [SMALL_STATE(13)] = 285,
  [SMALL_STATE(14)] = 310,
  [SMALL_STATE(15)] = 335,
  [SMALL_STATE(16)] = 357,
  [SMALL_STATE(17)] = 379,
  [SMALL_STATE(18)] = 401,
  [SMALL_STATE(19)] = 423,
  [SMALL_STATE(20)] = 440,
  [SMALL_STATE(21)] = 454,
  [SMALL_STATE(22)] = 468,
  [SMALL_STATE(23)] = 484,
  [SMALL_STATE(24)] = 500,
  [SMALL_STATE(25)] = 514,
  [SMALL_STATE(26)] = 528,
  [SMALL_STATE(27)] = 540,
  [SMALL_STATE(28)] = 554,
  [SMALL_STATE(29)] = 568,
  [SMALL_STATE(30)] = 584,
  [SMALL_STATE(31)] = 598,
  [SMALL_STATE(32)] = 612,
  [SMALL_STATE(33)] = 624,
  [SMALL_STATE(34)] = 636,
  [SMALL_STATE(35)] = 650,
  [SMALL_STATE(36)] = 664,
  [SMALL_STATE(37)] = 678,
  [SMALL_STATE(38)] = 692,
  [SMALL_STATE(39)] = 706,
  [SMALL_STATE(40)] = 720,
  [SMALL_STATE(41)] = 734,
  [SMALL_STATE(42)] = 746,
  [SMALL_STATE(43)] = 759,
  [SMALL_STATE(44)] = 772,
  [SMALL_STATE(45)] = 785,
  [SMALL_STATE(46)] = 798,
  [SMALL_STATE(47)] = 809,
  [SMALL_STATE(48)] = 822,
  [SMALL_STATE(49)] = 835,
  [SMALL_STATE(50)] = 848,
  [SMALL_STATE(51)] = 861,
  [SMALL_STATE(52)] = 871,
  [SMALL_STATE(53)] = 881,
  [SMALL_STATE(54)] = 891,
  [SMALL_STATE(55)] = 901,
  [SMALL_STATE(56)] = 911,
  [SMALL_STATE(57)] = 921,
  [SMALL_STATE(58)] = 931,
  [SMALL_STATE(59)] = 941,
  [SMALL_STATE(60)] = 951,
  [SMALL_STATE(61)] = 961,
  [SMALL_STATE(62)] = 971,
  [SMALL_STATE(63)] = 981,
  [SMALL_STATE(64)] = 991,
  [SMALL_STATE(65)] = 1001,
  [SMALL_STATE(66)] = 1011,
  [SMALL_STATE(67)] = 1021,
  [SMALL_STATE(68)] = 1025,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_block_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_block_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_block_repeat1, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_block_repeat1, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 3, 0, 2),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 3, 0, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 4, 0, 2),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 4, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_block_repeat1, 1, 0, 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_block_repeat1, 1, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_block, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document_block, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_twxml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "twxml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
